.\" Manpage for mediaplayer.
.\" Contact arnaud.marcantoine@gmail.com to correct errors or typos.
.TH man 1 "21 May 2014" "1.0" "mediaplayer man page"
.SH NOM
mediaplayer - play media file
.SH SYNOPSIS
mediaplayer inputfile.ext
.SH AUTHOR
Written by Marc-Antoine ARNAUD (arnaud.marcantoine@gmail.com)
.SH COPYRIGHT
Licence GPL-v3.0+
