.\" Manpage for avprofiles.
.\" Contact arnaud.marcantoine@gmail.com to correct errors or typos.
.TH man 1 "21 May 2014" "1.0" "avinfo man page"
.SH NOM
avprofiles - check options for each profile detected
.SH SYNOPSIS
avprofiles
.SH AUTHOR
Written by Marc-Antoine ARNAUD (arnaud.marcantoine@gmail.com)
.SH COPYRIGHT
Licence GPL-v3.0+
