import os
import platform

Import( 'env' )
Import( 'envJava' )
Import( 'mymode' )
Import( 'jAvTranscoder' )
Import( 'jAvTranscoderClass' )
Import( 'installPrefix' )

if jAvTranscoderClass:
	envJava.Append( 
		JAVACLASSPATH = '.:build/'+mymode+'/src/jAvTranscoderClass/'
	)

	#javtest_class = envJava.Java(
	#	target = 'javtestclass',
	#	source = Glob( 'jTranscoder/*.java')
	#)
	#env.Depends( javtest_class, jAvTranscoder )
