.\" Manpage for mediainfo.
.\" Contact arnaud.marcantoine@gmail.com to correct errors or typos.
.TH man 1 "21 May 2014" "1.0" "mediainfo man page"
.SH NOM
mediainfo - display version informations
.SH SYNOPSIS
mediainfo
.SH AUTHOR
Written by Marc-Antoine ARNAUD (arnaud.marcantoine@gmail.com)
.SH COPYRIGHT
Licence GPL-v3.0+
