Import( 'AvTranscoder' )
Import( 'sAvTranscoder' )
#Import( 'AvTranscoder_jar' )

env = Environment().Clone()

Import( 'env' )

avmeta = env.Program(
        'avmeta',
        Glob( 'avMeta/*.cpp' ),
        LIBS = [
                sAvTranscoder,
                'avutil',
                'avformat',
                'avcodec',
                'swscale',
                ]
        )

env.Program(
        'av++',
        Glob( 'avTranscoder/*.cpp' ),
        LIBS = [
                sAvTranscoder,
                'avutil',
                'avformat',
                'avcodec',
                'swscale',
                ]
        )

env.Depends( avmeta, sAvTranscoder )
