import os
import platform

Import( 'AvTranscoder' )
Import( 'sAvTranscoder' )
#Import( 'AvTranscoder_jar' )
Import( 'installPrefix' )

env = Environment().Clone()

Import( 'env' )

avinfo = env.Program(
        'avinfo',
        Glob( 'avInfo/*.cpp' ),
        LIBS = [
                sAvTranscoder,
                'avutil',
                'avformat',
                'avcodec',
                'swscale',
                ]
        )

avmeta = env.Program(
        'avmeta',
        Glob( 'avMeta/*.cpp' ),
        LIBS = [
                sAvTranscoder,
                'avutil',
                'avformat',
                'avcodec',
                'swscale',
                ]
        )

avtransform = env.Program(
        'av++',
        Glob( 'avTranscoder/*.cpp' ),
        LIBS = [
                sAvTranscoder,
                'avutil',
                'avformat',
                'avcodec',
                'swscale',
                ]
        )

avprocessor = env.Program(
        'avprocessor',
        Glob( 'genericProcessor/*.cpp' ),
        LIBS = [
                sAvTranscoder,
                'avutil',
                'avformat',
                'avcodec',
                'swscale',
                ],
        CXXFLAGS = [
                '-std=c++0x'
                ],
        )

audioRewrapper = env.Program(
        'audioWrap',
        Glob( 'audioRewrapper/*.cpp' ),
        LIBS = [
                sAvTranscoder,
                'avutil',
                'avformat',
                'avcodec',
                'swscale',
                ]
        )

if platform.system() != 'Windows':
        avplayer = env.Program(
                'avplayer',
                Glob( 'avplay/*.cpp' ),
                LIBS = [
                        sAvTranscoder,
                        'avutil',
                        'avformat',
                        'avcodec',
                        'swscale',
                        'GL',
                        'glut',
                        ]
                )


avprofiles = env.Program(
        'avprofiles',
        Glob( 'presetChecker/*.cpp' ),
        LIBS = [
                sAvTranscoder,
                'avutil',
                'avformat',
                'avcodec',
                'swscale'
                ],
        CXXFLAGS = [
                '-std=c++0x'
                ],
        )

env.Depends( avmeta, sAvTranscoder )
env.Depends( audioRewrapper, sAvTranscoder )

env.Alias( "install", env.Install(os.path.join( installPrefix, "bin" ), avmeta ) )
env.Alias( "install", env.Install(os.path.join( installPrefix, "bin" ), avprocessor ) )
env.Alias( "install", env.Install(os.path.join( installPrefix, "bin" ), avtransform ) )
env.Alias( "install", env.Install(os.path.join( installPrefix, "bin" ), audioRewrapper ) )
