.\" Manpage for avplay.
.\" Contact arnaud.marcantoine@gmail.com to correct errors or typos.
.TH man 1 "21 May 2014" "1.0" "avplay man page"
.SH NOM
avplay - play media file
.SH SYNOPSIS
avplay inputfile.ext
.SH AUTHOR
Written by Marc-Antoine ARNAUD (arnaud.marcantoine@gmail.com)
.SH COPYRIGHT
Licence GPL-v3.0+
