.\" Manpage for mediachecker.
.\" Contact arnaud.marcantoine@gmail.com to correct errors or typos.
.TH man 1 "21 May 2014" "1.0" "mediachecker man page"
.SH NOM
mediachecker - check options for each profile detected
.SH SYNOPSIS
mediachecker
.SH AUTHOR
Written by Marc-Antoine ARNAUD (arnaud.marcantoine@gmail.com)
.SH COPYRIGHT
Licence GPL-v3.0+
