.\" Manpage for avprocessor.
.\" Contact arnaud.marcantoine@gmail.com to correct errors or typos.
.TH man 1 "21 May 2014" "1.0" "avprocessor man page"
.SH NOM
avprocessor - process media files
.SH DESCRIPTION
Transcode or rewrap media files
.SH AUTHOR
Written by Marc-Antoine ARNAUD <arnaud.marcantoine@gmail.com>
.SH COPYRIGHT
Licence GPL-v3.0+
.SH SEE ALSO
.B ffmpeg
