
import glob, re

Import( "env" )
Import( "envJava" )
Import( "envPy" )

AvTranscoder = env.SharedLibrary(
    'AvTranscoder',
    Glob( 'AvTranscoder/*.cpp' ),
    LIBS = [
        'libavcodec'
    ]
)

jAvTranscoder = envJava.SharedLibrary(
                'jAvTranscoder',
                [
                        'AvTranscoder/avTranscoder.i'
                ],
                LIBS=[ AvTranscoder ],
        )

pyAvTranscoder = envPy.SharedLibrary(
                'AvTranscoder',
                [
                        'AvTranscoder/avTranscoder.i'
                ],
                LIBS=[ AvTranscoder ],
        )

env['JARCHDIR'] = env.Dir('#/build/src/jAvTranscoder').get_abspath()

compiled_classes = env.Java(
    target ='jAvTranscoder',
    source = Glob( '#/build/src/AvTranscoder' ) )

new_jar = env.Jar( target = "jAvTranscoder.jar", source = 'jAvTranscoder' )

Export( { 'AvTranscoder': AvTranscoder } )
Export( { 'jAvTranscoder': jAvTranscoder } )