.\" Manpage for avplayer.
.\" Contact arnaud.marcantoine@gmail.com to correct errors or typos.
.TH man 1 "21 May 2014" "1.0" "avinfo man page"
.SH NOM
avplayer - play media file
.SH SYNOPSIS
avplayer inputfile.ext
.SH AUTHOR
Written by Marc-Antoine ARNAUD (arnaud.marcantoine@gmail.com)
.SH COPYRIGHT
Licence GPL-v3.0+
